# Generated by Django 6.0.1 on 2026-02-07 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0003_category_alter_choice_options_alter_question_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='invited_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this private poll', related_name='invited_polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
